apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-frontend.fullname" . }}
  labels:
    {{- include "todo-frontend.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ .Values.env.databaseUrl | quote }}
  better-auth-secret: {{ .Values.env.betterAuthSecret | quote }}
