apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
scopes:
- recurring-task-service
spec:
  type: state.postgresql
  version: v1
  metadata:
  - name: connectionString
    secretKeyRef:
      name: postgres-secrets
      key: connectionString
  - name: table
    value: "state_phase5"
  - name: primaryKeyColumn
    value: "key"
  - name: valueColumn
    value: "value"
  - name: etagColumn
    value: "etag"
  - name: consumerIDColumn
    value: "consumerid"
  - name: updateRowFormat
    value: "jsonb"
  - name: cleanupInterval
    value: "60m"
  - name: schema
    value: "dapr"
auth:
  secretStore: kubernetes
